// Accommodation options for the trip (13 - 15 November 2026).
// Each option is displayed as a card, plotted on the map and can be voted on.
//
// Fields:
//   id        unique key (used for voting state) - do NOT change once people have voted
//   name      display title
//   region    used for the coloured badge / gradient
//   town      approximate location text
//   persons   max sleeping capacity
//   bedrooms  number of bedrooms
//   price      total price for the stay (null = "op aanvraag" / request via site)
//   nights     number of nights the price covers (for a fair comparison)
//   pets       true / false
//   rating     guest review score (out of 10) or null
//   coords     [latitude, longitude] for the map marker
//   link       url to the accommodation page
//   perks      list of nice-to-have highlights

const OPTIONS = [
  {
    id: "texel-natuurhuisje",
    name: "Off-grid Natuurhuisje (villa)",
    region: "Texel",
    town: "Den Burg (midden Texel)",
    persons: 12,
    bedrooms: 6,
    price: 2132,
    nights: 2,
    pets: false,
    rating: 8.7,
    coords: [53.0553, 4.7953],
    image: "https://nature.house/cdn-cgi/imagedelivery/8Ahqf8RmIwfc0e1N5qGmxg/fff08403-c879-4aa2-ad24-31ac71be5400/rotate=0,fit=cover,width=760,height=490",
    link: "https://www.natuurhuisje.nl/vakantiehuisje/33101?arrivalDate=2026-11-13&departureDate=2026-11-15&adults=10",
    perks: [
      "Elke slaapkamer eigen luxe badkamer",
      "Sauna + whirlpool/ligbad",
      "Ecologische zwemvijver op landgoed",
      "Open haard / houtkachel",
      "100% duurzaam & off-grid, Green Key Gold",
      "Adembenemend uitzicht over Texel",
    ],
  },
  {
    id: "overijssel-debult",
    name: "Boswachterswoning De Bult (EES-1807)",
    region: "Overijssel",
    town: "De Bult, bij Nat. Park Weerribben-Wieden",
    persons: 12,
    bedrooms: 6,
    price: null,
    nights: 2,
    pets: true,
    rating: 8.5,
    coords: [52.7897, 6.0286],
    image: "https://cdn.bookzoapi.nl/groepennl/26461_800.webp",
    link: "https://www.groepen.nl/groepsaccommodaties/nederland/overijssel/de-bult/ees-1807",
    perks: [
      "100+ jaar oud, Engelse cottage-stijl",
      "Grote tuin met 2 terrassen",
      "Buitenzwembad & restaurant op het park",
      "Aan de rand van nationaal park",
      "Huisdieren toegestaan",
      "Slechts 25% aanbetaling",
    ],
  },
  {
    id: "texel-koornaar",
    name: "De Koorn-aar Groepsvilla",
    region: "Texel",
    town: "De Dennen (bij bos), Texel",
    persons: 12,
    bedrooms: 6,
    price: 1215,
    nights: 2,
    pets: true,
    rating: 8.6,
    coords: [53.064764, 4.762295],
    image: "https://texel-cdn.travelbase.nl/image-transforms/tile/896x672/e1ff872c4b4f297101886b1042c2594c.jpeg",
    link: "https://www.texel.net/nl/accommodatie/koornaar-8220/",
    perks: [
      "Twee privé Finse sauna's",
      "4 badkamers, 6 toiletten",
      "Luxe: QLED-tv met Netflix, Nespresso",
      "Vloerverwarming",
      "Aan de rand van het bos, 10 min. fietsen naar strand",
      "Huisdieren toegestaan (max. 2)",
    ],
  },
  {
    id: "texel-bornrif",
    name: "Stolp Nieuw Bornrif",
    region: "Texel",
    town: "De Koog, Texel",
    persons: 12,
    bedrooms: 6,
    price: 1672,
    nights: 2,
    pets: false,
    rating: 8.3,
    coords: [53.097745, 4.774029],
    image: "https://texel-cdn.travelbase.nl/image-transforms/tile/896x672/970d1e6384f5e12abe0058164507448a.jpeg",
    link: "https://www.texel.net/nl/accommodatie/stolp-nieuw-bornrif-5246/",
    perks: [
      "Sfeervolle stolpboerderij",
      "Aparte speelkamer (airhockey, Lego, Playmobil)",
      "Open haard + ligbad",
      "Dieren op het erf, speelveld ernaast",
      "Grote tuin met terras",
      "Strand De Koog op fietsafstand",
    ],
  },
  {
    id: "zeeland-64119856",
    name: "Vakantiehuis Zeeland (voordelig)",
    region: "Zeeland",
    town: "Zeeland",
    persons: 10,
    bedrooms: null,
    price: 912,
    nights: 2,
    pets: null,
    rating: null,
    coords: [51.4920, 3.8400],
    image: "https://img.holidu.com/images/861c42d9-d752-4ffe-a26b-f677c35be0d0/t.jpg",
    link: "https://www.vakantiehuisje.nl/d/64119856?checkin=2026-11-13&checkout=2026-11-15&adults=10",
    perks: [
      "Goedkoopste optie in de lijst",
      "Ruimte voor 10 personen",
      "Zeeland: kust & rust",
    ],
  },
  {
    id: "zeeland-63491397",
    name: "Vakantiehuis Zeeland (met sauna)",
    region: "Zeeland",
    town: "Zeeland",
    persons: 10,
    bedrooms: null,
    price: 1595,
    nights: 2,
    pets: null,
    rating: null,
    coords: [51.5010, 3.8650],
    image: "https://img.holidu.com/images/ba2670b6-ef2e-4754-ad25-ed31a433b9e8/t.jpg",
    link: "https://www.vakantiehuisje.nl/d/63491397?checkin=2026-11-13&checkout=2026-11-15&adults=10",
    perks: [
      "Eigen sauna",
      "Ruimte voor 10 personen",
      "Zeeland: kust & rust",
    ],
  },
  {
    id: "terschelling-willemshoeve",
    name: "Vakantiehuis Willemshoeve",
    region: "Terschelling",
    town: "Lies, Terschelling",
    persons: 11,
    bedrooms: 5,
    price: 1117,
    nights: 3,
    pets: null,
    rating: null,
    coords: [53.3990, 5.3510],
    image: "https://op-terschelling.nl/av_fotos/huis/t/th-willemshoeve/foto-1.jpg",
    link: "https://op-terschelling.nl/-/Vakantiehuis.Willemshoeve/-8-11-persoons-vakantiehuis-met-grote-tuin-in-Lies?gezelschap=10;0;0;0;0;0&startdatum=13-11-2026&einddatum=16-11-2026",
    perks: [
      "Grote tuin",
      "8 - 11 persoons",
      "3 nachten (13 - 16 nov)",
    ],
  },
  {
    id: "terschelling-roodkapje",
    name: "Vakantiehuis Roodkapje",
    region: "Terschelling",
    town: "Formerum (in de duinen)",
    persons: 11,
    bedrooms: null,
    price: 1637,
    nights: 3,
    pets: null,
    rating: null,
    coords: [53.4080, 5.3860],
    image: "https://op-terschelling.nl/av_fotos/huis/t/th-roodkapje/foto-1.jpg",
    link: "https://op-terschelling.nl/-/Vakantiehuis.Roodkapje/-11-persoons-vakantiehuis-in-de-duinen-bij-Formerum?gezelschap=10;0;0;0;0;0&startdatum=13-11-2026&einddatum=16-11-2026",
    perks: [
      "Midden in de duinen",
      "11 persoons",
      "3 nachten (13 - 16 nov)",
    ],
  },
  {
    id: "terschelling-borndiep",
    name: "Landhuis Huys Borndiep ⭐",
    region: "Terschelling",
    town: "Hoorn, Terschelling",
    persons: 16,
    bedrooms: 7,
    price: 1808,
    nights: 3,
    pets: null,
    rating: null,
    coords: [53.3720, 5.4630],
    image: "https://op-terschelling.nl/av_fotos/huis/t/th-borndiephoorn/foto-1.jpg",
    link: "https://op-terschelling.nl/-/Vakantiehuis.Huys.Borndiep/-landhuis-voor-16-personen-in-Hoorn?gezelschap=10;0;0;0;0;0&startdatum=13-11-2026&einddatum=16-11-2026",
    perks: [
      "Favoriet: heel leuk landhuis",
      "Ruim: tot 16 personen, 7 slaapkamers",
      "3 nachten (13 - 16 nov)",
    ],
  },
  {
    id: "terschelling-westend",
    name: "Vakantieboerderij West End Zuid",
    region: "Terschelling",
    town: "Hee (bij West-Terschelling)",
    persons: 12,
    bedrooms: 5,
    price: 2119,
    nights: 3,
    pets: null,
    rating: null,
    coords: [53.3620, 5.2830],
    image: "https://op-terschelling.nl/av_fotos/huis/t/th-westendzuid/foto-1.jpg",
    link: "https://op-terschelling.nl/-/Vakantiehuis.WestEnd.Zuid/-Luxe-10-12p-vakantieboerderij-in-het-dorp-Hee--nabij-West-Terschelling?gezelschap=10;0;0;0;0;0&startdatum=13-11-2026&einddatum=16-11-2026",
    perks: [
      "Luxe vakantieboerderij, 10 - 12 personen",
      "In het dorpje Hee",
      "3 nachten (13 - 16 nov)",
    ],
  },
];

// Colour theme per region (used for badges and map markers)
const REGION_COLORS = {
  Texel: "#2a9d8f",
  Overijssel: "#8a5a44",
  Zeeland: "#457b9d",
  Terschelling: "#e76f51",
};
